matrix:
    include:
        # test
        -   os: linux
            language: node_js
            node_js:
                - 8
            install:
                - yarn --version
                - yarn install
            script:
                - yarn lint
        # scrape period 19 Laws 100
        -   if: branch =~ ^master OR branch =~ /^pr\..*/
            os: linux
            language: node_js
            node_js:
                - 8
            install:
                - yarn --version
                - yarn install
            script:
                - yarn start -p 19 -t 100
after_script:
  - echo "BUILD FINISHED"